### ISSUE TITLE
``dtool ls`` doesn't work with relative paths

### ISSUE THREAD

**Issue by mrmh2** [jic-dtool/dtool-info#2]
dtool ls . produces the following:

```(dtool) N108176:uauyc_cell_size_measurement hartleym$ dtool ls .
Traceback (most recent call last):
  File "/Users/hartleym/virtualenvs/dtool/bin/dtool", line 11, in <module>
    sys.exit(dtool())
  File "/Users/hartleym/virtualenvs/dtool/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/hartleym/virtualenvs/dtool/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/hartleym/virtualenvs/dtool/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/hartleym/virtualenvs/dtool/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/hartleym/virtualenvs/dtool/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/hartleym/virtualenvs/dtool/lib/python2.7/site-packages/dtool_info/dataset.py", line 97, in ls
    admin_metadata = dtoolcore._admin_metadata_from_uri(uri, CONFIG_PATH)
  File "/Users/hartleym/virtualenvs/dtool/lib/python2.7/site-packages/dtoolcore/__init__.py", line 48, in _admin_metadata_from_uri
    admin_metadata = storage_broker.get_admin_metadata()
  File "/Users/hartleym/virtualenvs/dtool/lib/python2.7/site-packages/dtoolcore/storagebroker.py", line 102, in get_admin_metadata
    with open(self._admin_metadata_fpath) as fh:
IOError: [Errno 2] No such file or directory: '/derived_from_example_lif_2017/.dtool/dtool'
```

**Comment by tjelvar-olsson** [comment]
Fixed in 2792494
